###### spring ######
spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
  servlet:
    multipart:
      max-file-size: 1000MB  # 파일 하나당 최대 크기
      max-request-size: 10000MB  # 요청당 최대 크기

  ###### 운영/개발 환경 분리 ######
  config:
    activate:
      on-profile: dev

  ###### Database ######
  datasource:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://218.152.205.17:5432/srilanka
    #username: srilanka
    #password: bluedus1!
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://211.189.132.15:4143/LKDB
    username: LKDB
    password: LKDB


  ###### jpa properties ######
  jpa:
    #hibernate:
    #ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: srlk
        format_sql: true # SQL문 정렬하여 출력
    database: postgresql
    database-platform: com.sl.tdbms.web.admin.config.postgres.PostgresSqlDialectConfig
    open-in-view: false
    generate-ddl: false
  
###### srilanka ######
srilanka:
  kecc:
    auth:
      role: kecc
  developer:
    auth:
      role: developer
  auth:
    role: mngr
  messages:
    basename: messages/login/login,messages/main/main,messages/validation/validation,messages/common/common,messages/api/api,messages/authRqst/authRqst,messages/code/code,messages/menu/menu,messages/mngr/mngr,messages/dataRegist/dataRegist,messages/alarm/alarm,messages/survey/survey,messages/invest/invest,messages/schedule/schedule,messages/mypage/mypage,messages/board/board,messages/facilities/facilities,messages/dataRegist/dataRegist,messages/statistics/statistics,messages/enums/enums,messages/faq/faq,messages/nbmetrocount/metrocount,messages/nbstatisticsdown/statisticsdown,messages/region/region
    encoding: UTF-8
  main:
    url: http://211.189.132.16:58081
  mail:
    sender: RDA_ADMIN

###### fileUpload ######
file.upload.path: C:\test_files\
file.sample.download.path: C:\test_files\

###### server ######
server:
  port: 8080
  servlet:
    session:
      persistent: false
      cookie:
        name: SRLKAID
  error:
    whitelabel:
      enabled: false
    path: /error

logging:
  level:
    root: ERROR
    com.sl.tdbms.web.admin: DEBUG
